//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use rocket::serde::{Deserialize, Serialize};
use sea_orm::entity::prelude::*;
use query_builder_macro::QueryBuilder;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, QueryBuilder)]
#[sea_orm(table_name = "account")]
#[serde(crate = "rocket::serde")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub username: String,
    pub email: String,
    pub password: String,
    pub admin: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
